### ISSUE TITLE
Not able to inspect the any iOS sample flutter app in appium Inspector (and  appium 1.22.0) and iOS 14.7

### ISSUE THREAD

**Issue by narasimhanukala** [appium-userland/appium-flutter-driver#229] opened 2021-12-20 14:47 UTC
i build the sample app in profile mode and installed in device, then i tried to launch it using appium inspector with appium server 1.22.0,  with following capabilities. app gets launched in device but app screen in not loaded into Appium inspector.
can someone help me by providing a working flutter app for ios to play with it, as i have to start building automation framework.

Note: The flutter sample apps used from : (https://github.com/flutter/samples), 
{
  "appium:deviceName": "iPhone",
  "appium:udid": "069a19a81c7e4208b4281748dedccd5c718b74e6",
  "platformName": "iOS",
  "appium:platformVersion": "14.7.1",
  "appium:bundleId": "dev.flutter.testingApp",
  "appium:automationName": "Flutter",
  "appium:useNewWDA": true,
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:xcodeOrgId": "xxxxxxxx"
}

Appium Log Says: 
[W3C (7e01f39e)] Calling AppiumDriver.getWindowRect() with args: ["7e01f39e-c1f9-437d-b4eb-5e8f7c61406a"]
[FlutterDriver] Executing Flutter driver command 'getWindowRect'
[W3C (7e01f39e)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented

The server is running
[W3C (89c8181a)] Cached the protocol value 'W3C' for the new session 89c8181a-9401-4411-9f1e-a54d085bc223
[W3C (89c8181a)] Responding to client with driver.createSession() result: {"capabilities":{"shell":false,"allowCors":false,"reboot":false,"ipa":null,"address":"0.0.0.0","port":4723,"basePath":"/wd/hub","keepAliveTimeout":null,"callbackAddress":null,"callbackPort":null,"bootstrapPort":4724,"backendRetries":3,"sessionOverride":false,"launch":false,"logFile":null,"loglevel":"debug","logTimestamp":false,"localTimezone":false,"logNoColors":false,"webhook":null,"safari":false,"defaultDevice":false,"forceIphone":false,"forceIpad":false,"automationTraceTemplatePath":null,"instrumentsPath":null,"nodeconfig":null,"robotAddress":"0.0.0.0","robotPort":-1,"chromedriverExecutable":null,"showConfig":false,"noPermsCheck":false,"enforceStrictCaps":false,"isolateSimDevice":false,"tmpDir":"/var/folders/wf/b4f4pvxd2gv9th6csmctxpnr0000gn/T","traceDir":null,"debugLogSpacing":false,"suppressKillServer":false,"longStacktrace":false,"webkitDebugProxyPort":27753,"wdaLocalPort":8100,"defaultCapabilities":{},"relaxedSecurityEnabled":true,"allowInsecure":[],"denyInsecure":[],"defaultCommandTimeout":60,"keep...
[HTTP] <-- POST /wd/hub/session 200 39541 ms - 2292
[HTTP] 
[HTTP] --> GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/screenshot
[HTTP] {}
[W3C (89c8181a)] Calling AppiumDriver.getScreenshot() with args: ["89c8181a-9401-4411-9f1e-a54d085bc223"]
[FlutterDriver] Executing Flutter driver command 'getScreenshot'
[W3C (89c8181a)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABNoAAAigCAYAAADpkk+ZAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15eB112f/xz8ycLUmbJg1p073pvqQtpTu0UChtgYKyKoogIirooyggKu6i4sOjPogIuIGo/EDBBwTLXspOWUppaWnpQle6p1ua5Wwzvz8OgZycmZOTZLK179d1cYmlydnnzHy+9/e+jfLbqhwBAAAAAAAAaBWzo+8AAAAAAAAAcCQgaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAAAAAAAD4gaAMAAAAAAAB8QNAGAAAAAAAA+ICgDQAAAAAAAPABQRsAAAAAAADgA4I2AAAAAAAAwAcEbQAAAAAAAIAPCNoAAAAAAAAAHxC0AQAA...
[HTTP] <-- GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/screenshot 200 239 ms - 140980
[HTTP] 
[HTTP] --> GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/window/rect
[HTTP] {}
[W3C (89c8181a)] Calling AppiumDriver.getWindowRect() with args: ["89c8181a-9401-4411-9f1e-a54d085bc223"]
[FlutterDriver] Executing Flutter driver command 'getWindowRect'
[W3C (89c8181a)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C (89c8181a)]     at FlutterDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)
[W3C (89c8181a)]     at FlutterDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:132:22)
[W3C (89c8181a)]     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)
[W3C (89c8181a)]     at runMicrotasks ()
[W3C (89c8181a)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C (89c8181a)]     at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/window/rect 405 2 ms - 928
[HTTP] 
[HTTP] --> GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/source
[HTTP] {}
[W3C (89c8181a)] Calling AppiumDriver.getPageSource() with args: ["89c8181a-9401-4411-9f1e-a54d085bc223"]
[FlutterDriver] Executing Flutter driver command 'getPageSource'
[W3C (89c8181a)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C (89c8181a)]     at FlutterDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)
[W3C (89c8181a)]     at FlutterDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:132:22)
[W3C (89c8181a)]     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)
[W3C (89c8181a)]     at runMicrotasks ()
[W3C (89c8181a)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C (89c8181a)]     at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/source 405 1 ms - 928
[HTTP] 
[HTTP] --> GET /wd/hub/session/89c8181a-9401-4411-9f1e-a54d085bc223/timeouts
[HTTP] {}

![image](https://user-images.githubusercontent.com/45284113/146785080-00d826ca-7d6f-4cbc-8915-a2bed30e9715.png)

**Comment by KazuCocoa** [comment] 2021-12-21 05:47
It is because flutter-driver's page_source does not respond XML format as https://github.com/appium-userland/appium-flutter-driver#note (getRenderTree just returns a string)

**Comment by narasimhanukala** [comment] 2021-12-21 12:35
Hi @KazuCocoa 
in this case, what would be the solution?
How should i proceed?
any help would be appreciated..

**Comment by shibupanda** [comment] 2021-12-21 12:57
Hi @narasimhanukala there is two way to proceed and folks are using that approach too.
1. Get all relevant locators from dev team
2. Get the source code and by using flutter inspector inspect element and get the relevant locators.

**Comment by narasimhanukala** [comment] 2021-12-21 13:47
Thanks @shibupanda . 
i will explore on the above said two options.
i have a basic question,
can we automate the ios app designed in flutter technology using appium tool but without using appium flutter driver? are there any challenges?

**Comment by KazuCocoa** [comment] 2021-12-23 07:29
> can we automate the ios app designed in flutter technology using appium tool but without using appium flutter driver? are there any challenges?

Yes, for a release build as well. Possibly changing accessibility preference may help. https://appium.io/docs/en/drivers/ios-xcuitest/#accessibility-preferences-fine-tuning

Appium flutter driver requires a debug/profile mode, but it does not work for a release build.
XCUITest driver may help then.

**Comment by sanneabhilash** [comment] 2021-12-23 10:22
@narasimhanukala  you should be able to inspect the elements in the below two scenarios:

- Using BrowserStack AppLive feature called Inspect (Beta)
- Emulating a device using Android Studio, but ensure automationName is not set to Flutter.
If the app launches with the automationName as Flutter you won't be able to inspect, kill it and open it again manually in your local emulator,

**Comment by KazuCocoa** [comment] 2022-01-08 07:50
Duplicate of https://github.com/appium-userland/appium-flutter-driver/issues/56 (the inspector integration itself)

**Closed by KazuCocoa** 2022-01-08 07:50 UTC
