### ISSUE TITLE
Flutter Exception in thread "main" java.lang.NoClassDefFoundError: io/appium/java_client/MobileElement

### ISSUE THREAD

**Issue by RYenike** [appium-userland/appium-flutter-driver#517] opened 2023-08-04 12:06 UTC
import java.io.FileWriter;

import java.net.MalformedURLException;

import java.net.URL;

import java.time.Duration;

 

import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumBy;

import io.appium.java_client.android.AndroidDriver;

import pro.truongsinh.appium_flutter.FlutterFinder;

import pro.truongsinh.appium_flutter.finder.FlutterElement;

DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("appium:platformVersion", "11");

        capabilities.setCapability("appium:deviceName","Mi A3");

        capabilities.setCapability("platformName", "Android");

        capabilities.setCapability("appium:appPackage", "xxxxxx");

        capabilities.setCapability("appium:appActivity", "xxxxx");

        capabilities.setCapability("unlockType", "pin");

        capabilities.setCapability("unlockKey", "2580");

             capabilities.setCapability("automationName", "Flutter");
 

            URL remoteUrl = new URL("http://127.0.0.1:4723");

            AndroidDriver driver = new AndroidDriver(remoteUrl, capabilities);

            driver.manage().timeouts().implicitlyWait(Duration.ofMinutes(1));

                    

            driver.context("NATIVE_APP");

            driver.findElement(AppiumBy.id("com.android.permissioncontroller:id/permission_allow_one_time_button")).click();

            driver.findElement(AppiumBy.xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.ImageView[1]")).click();

          

            driver.context("FLUTTER");

 

            FlutterFinder find = new FlutterFinder(driver);

            FlutterElement clikSignIn = find.text("Sign in");

At this find.text() line got error 
**Flutter Exception in thread "main" java.lang.NoClassDefFoundError: io/appium/java_client/MobileElement**

[DEBUG] Adding key: http://127.0.0.1:4723/ for channel [id: 0xdff06a0e, L:/127.0.0.1:51942 - R:/127.0.0.1:4723]

Exception in thread "main" java.lang.NoClassDefFoundError: io/appium/java_client/MobileElement

    at java.base/java.lang.ClassLoader.defineClass1(Native Method)

    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)

    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)

    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)

    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)

    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)

    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)

    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

    at pro.truongsinh.appium_flutter.finder._FinderRawMethods__TextKt.text(text.kt:6)

    at pro.truongsinh.appium_flutter.finder._FinderRawMethods.text(Unknown Source)

    at pro.truongsinh.appium_flutter.FlutterFinder.text(FlutterFinder.kt:90)

    at StepDefinition.FlutterClass.main(FlutterClass.java:79)

Caused by: java.lang.ClassNotFoundException: io.appium.java_client.MobileElement

    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)

    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

    ... 13 more
    
    
POM.xml

<?xml version="1.0" encoding="UTF-8"?>

 

<project xmlns="http://maven.apache.org/POM/4.0.0"

    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

 

    <groupId>CucumberFramework</groupId>

    <artifactId>CucumberFramework</artifactId>

    <version>0.0.1-SNAPSHOT</version>

 

    <name>CucumberFramework</name>

    

    <url>http://www.example.com</url>

 

    <properties>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>1.7</maven.compiler.source>

        <maven.compiler.target>1.7</maven.compiler.target>

    </properties>

    <dependencies>

        <dependency>

            <groupId>junit</groupId>

            <artifactId>junit</artifactId>

            <version>4.11</version>

            <scope>test</scope>

        </dependency>

 

        

        <dependency>

            <groupId>io.cucumber</groupId>

            <artifactId>cucumber-html</artifactId>

            <version>0.2.7</version>

        </dependency>

 

        

        <dependency>

            <groupId>net.sourceforge.cobertura</groupId>

            <artifactId>cobertura</artifactId>

            <version>2.1.1</version>

            <scope>test</scope>

        </dependency>

        

        <dependency>

            <groupId>io.cucumber</groupId>

            <artifactId>cucumber-java</artifactId>

            <version>7.3.4</version>

        </dependency>

        

        

        <dependency>

            <groupId>io.cucumber</groupId>

            <artifactId>cucumber-jvm-deps</artifactId>

            <version>1.0.6</version>

            <scope>provided</scope>

        </dependency>

        

        <dependency>

            <groupId>net.masterthought</groupId>

            <artifactId>cucumber-reporting</artifactId>

            <version>5.7.1</version>

        </dependency>

        

        <dependency>

            <groupId>org.hamcrest</groupId>

            <artifactId>hamcrest-core</artifactId>

            <version>2.2</version>

            <scope>test</scope>

        </dependency>

        

        <dependency>

            <groupId>io.cucumber</groupId>

            <artifactId>gherkin</artifactId>

            <version>23.0.1</version>

        </dependency>

 

        <dependency>

            <groupId>org.seleniumhq.selenium</groupId>

            <artifactId>selenium-java</artifactId>

            <version>4.10.0</version>

        </dependency>

 

        

        <dependency>

            <groupId>io.github.bonigarcia</groupId>

            <artifactId>webdrivermanager</artifactId>

            <version>5.2.0</version>

        </dependency>

 

        <dependency>

            <groupId>com.sun</groupId>

            <artifactId>tools</artifactId>

            <version>1.5.0</version>

            <scope>system</scope>

            <systemPath>C:\Users\srthota\Automation\AmaronAutomationFramework\tools\tools.jar</systemPath>

        </dependency>

        

 

        

        <dependency>

            <groupId>commons-io</groupId>

            <artifactId>commons-io</artifactId>

            <version>2.11.0</version>

        </dependency>

 

        

        <dependency>

            <groupId>org.apache.logging.log4j</groupId>

            <artifactId>log4j-core</artifactId>

            <version>2.17.2</version>

        </dependency>

 

        

        <dependency>

            <groupId>org.apache.logging.log4j</groupId>

            <artifactId>log4j-api</artifactId>

            <version>2.17.2</version>

        </dependency>

 

        

        <dependency>

            <groupId>org.testng</groupId>

            <artifactId>testng</artifactId>

            <version>7.4.0</version>

            <scope>test</scope>

        </dependency>

 

        

        <dependency>

            <groupId>io.cucumber</groupId>

            <artifactId>cucumber-testng</artifactId>

            <version>7.3.4</version>

        </dependency>

        

 

<dependency>

    <groupId>io.qameta.allure</groupId>

    <artifactId>allure-testng</artifactId>

    <version>2.23.0</version>

</dependency>

 

 

        <dependency>

 

            <groupId>org.apache.poi</groupId>

 

            <artifactId>poi</artifactId>

 

            <version>5.2.3</version>

 

        </dependency>

 

 

        <dependency>

 

            <groupId>org.apache.poi</groupId>

 

            <artifactId>poi-ooxml</artifactId>

 

            <version>5.2.3</version>

 

        </dependency>

        

 

<dependency>

<groupId>org.jetbrains.kotlinx</groupId>

<artifactId>kotlinx-serialization-runtime</artifactId>

<version>0.14.0</version>

<scope>runtime</scope>

</dependency>

<dependency>

<groupId>io.appium</groupId>

<artifactId>java-client</artifactId>

<version>8.5.1</version>

</dependency>

 <dependency>
			<groupId>pro.truongsinh</groupId>
			<artifactId>appium-flutter-finder</artifactId>
			<version>0.0.4</version>
    </dependency>

 

    </dependencies>

    <build>

        <pluginManagement>

            <plugins>

                <plugin>

                    <groupId>org.apache.maven.plugins</groupId>

                    <artifactId>maven-surefire-plugin</artifactId>

                    <version>3.0.0-M7</version>

                    <configuration>

                        <testFailureIgnore>true</testFailureIgnore>

                        <includes>

                            <include>**/*Run.java</include>

                        </includes>

                    </configuration>

                </plugin>

            </plugins>

        </pluginManagement>

    </build>

</project>

**Comment by KazuCocoa** [comment] 2023-08-06 07:20
Perhaps duplicate of https://github.com/appium-userland/appium-flutter-driver/issues/265

**Closed by KazuCocoa** 2023-08-06 07:20 UTC

**Comment by RYenike** [comment] 2023-08-07 05:00
@KazuCocoa  Please provide me link to download the updated jar file with 0.0.4 its not working i think new version of jar is 0.0.5

**Comment by KazuCocoa** [comment] 2023-08-07 16:39
I'm not sure about the release process for Java/Kotlin finder. Let me see what i can do.

**Comment by hai-ha** [comment] 2023-12-19 15:41
@RYenike Hope you found your own way to solve the issue.
FYI, I released some recent versions on [my fork](https://github.com/hai-ha/appium-flutter-driver/releases) for personal use. You might take a look if necessary.

@KazuCocoa I think that was the missing part in Kotlin finder project: new code changes are not made releases. To my experience, it's just simple to create local Maven artifacts with a Gradle command:
```
gradlew publishToMavenLocal
```
Or via GUI: https://www.jetbrains.com/help/idea/add-a-gradle-library-to-the-maven-repository.html#publish
Then, however, we still need to create a GitHub release manually.
