### ISSUE TITLE
Checking whether a element is visible is not working

### ISSUE THREAD

**Issue by shr-avi** [appium-userland/appium-flutter-driver#151] opened 2021-04-15 12:43 UTC
Looks like is_displayed selenium function is not implemented yet. Can you please suggest a workaround for this

**Comment by KazuCocoa** [comment] 2021-09-13 06:34
As https://github.com/appium-userland/appium-flutter-driver/issues/103 , flutter_driver package does not provide such API, so I assume this driver (flutter context) cannot provide accurate behavior, technically.

One possible workaround is:

> For a work around you can use waitFor inside try..catch block.

by https://github.com/appium-userland/appium-flutter-driver/issues/103#issuecomment-713090147

Duplicate of https://github.com/appium-userland/appium-flutter-driver/issues/103

**Closed by KazuCocoa** 2021-09-13 06:34 UTC
