### ISSUE TITLE
appium-flutter-driver automated test Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by lztestjust** [appium-userland/appium-flutter-driver#171] opened 2021-08-10 01:33 UTC
> ## The problem
> Use appium to execute pure flutter APP to automatically report errors
> 
> ## Environment
> 1.Use npm install appium，Appium version is 1.21.0（with appium-flutter-driver）
> 2.Node.js version is v14.15.0
> 3.SDK Mobile platform/version is 29
> 4.Real Android device
> 5.python 3.7(install Appium-Python-Client,Appium-Flutter-Finder)
> 
> ## Details
> * 1.Start appium:
>   Start appium in cmd：appium
> * 2.Execute python testCase script:
>   from appium.webdriver import Remote
>   if **name** == '**main**':
>   ANDROID_FLUTTER_CAPS = {
>   'appPackage': '[appPackage]',
>   ‘appActivity’: '[appActivity]'
>   'automationName': 'Flutter',
>   'platformName': 'Android',
>   'platformVersion': '10.0',
>   'deviceName':  'Android Emulator'
>   }
>   driver = Remote('http://127.0.0.1:4723/wd/hub', desired_capabilities=ANDROID_FLUTTER_CAPS)
> * 3.the appium-site debug info:
>   [debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
>   [debug] [W3C]     at Object.exports.processLogToGetobservatory (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\build\driver\lib\sessions\observatory.js:118:9)
>   [debug] [W3C]     at Object.exports.getObservatoryWsUri (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:35:21)
>   [debug] [W3C]     at Object.exports.startAndroidSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:26:28)
>   [debug] [W3C]     at runMicrotasks ()
>   [debug] [W3C]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>   [debug] [W3C]     at FlutterDriver.exports.createSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\session.ts:18:47)
>   [debug] [W3C]     at AppiumDriver.createSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
>   [HTTP] <-- POST /wd/hub/session 500 8628 ms - 639
>   [HTTP]
>   ![1628503067(1)](https://user-images.githubusercontent.com/24455387/128691722-f97e91b1-afe9-49d9-a483-7d6acfcba965.png)
> * 4.appium-site logs:
>   [appium-site-log.txt](https://github.com/appium/appium/files/6953602/appium-site-log.txt)

**Comment by KazuCocoa** [comment] 2021-08-11 07:22
Did you ensure the app under test called `enableFlutterDriverExtension`? 
https://github.com/truongsinh/appium-flutter-driver#usage

**Comment by ferreirasouza** [comment] 2021-08-18 21:57
Hi Guys.

Does anyone know any solution for this problem?
I'm also facing the same problem, but for iOS.

I'm a QA and I asked dev team to enable Flutter Driver Extension, but I still have the same issue...

The log from Appium:

....
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1629321676325 (17:21:16 GMT-0400 (Eastern Daylight Time))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[debug] [W3C] at Object.exports.processLogToGetobservatory (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [W3C] at Object.exports.getObservatoryWsUri (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:31:21)
[debug] [W3C] at Object.exports.startIOSSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:23:34)
[debug] [W3C] at runMicrotasks ()
[debug] [W3C] at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C] at FlutterDriver.exports.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/session.ts:15:47)
[debug] [W3C] at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 26446 ms - 579
[HTTP]

Appium Doctor:

info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor ✔ Node version is 14.17.1
info AppiumDoctor ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor ✔ DevToolsSecurity is enabled.
info AppiumDoctor ✔ The Authorization DB is set up properly.
info AppiumDoctor ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 1.0.6
info AppiumDoctor ✔ HOME is set to: /Users/fabioghetler
info AppiumDoctor ✔ ANDROID_HOME is set to: /Users/fabioghetler/Library/Android/sdk
info AppiumDoctor ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
info AppiumDoctor Checking adb, android, emulator
info AppiumDoctor 'adb' is in /Users/fabioghetler/Library/Android/sdk/platform-tools/adb
info AppiumDoctor 'android' is in /Users/fabioghetler/Library/Android/sdk/tools/android
info AppiumDoctor 'emulator' is in /Users/fabioghetler/Library/Android/sdk/emulator/emulator
info AppiumDoctor ✔ adb, android, emulator exist: /Users/fabioghetler/Library/Android/sdk
info AppiumDoctor ✔ 'bin' subfolder exists under '/Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor ✖ ffmpeg cannot be found
WARN AppiumDoctor ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor ✖ set-simulator-location is not installed
WARN AppiumDoctor ✖ idb and idb_companion are not installed
info AppiumDoctor ✔ applesimutils is installed at: /usr/local/bin/applesimutils. Installed versions are: applesimutils 0.9.4
info AppiumDoctor ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.11.4
WARN AppiumDoctor ✖ bundletool.jar cannot be found
WARN AppiumDoctor ✖ gst-launch-1.0 and/or gst-inspect-1.0 cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 7 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor ➜ set-simulator-location is needed to set location for Simulator. Please read https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
WARN AppiumDoctor ➜ gst-launch-1.0 and gst-inspect-1.0 are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/ to install them and for more details
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

Thanks in advantage

**Comment by KazuCocoa** [comment] 2021-08-19 07:28
Please attach the full appium log as GIST

**Comment by KazuCocoa** [comment] 2021-09-09 22:45
duplicate of https://github.com/appium-userland/appium-flutter-driver/issues/82

**Closed by KazuCocoa** 2021-09-09 22:45 UTC
Labels: NeedInfo
